name: Publish

on: 
  push:
    tags:
    - '*'

jobs:

  publish-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Publish
      run: dotnet publish TES3Merge/TES3Merge.csproj -o publish/linux -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained false
    
    # create zip
    - run: ls -R
    - run: zip -r TES3Merge-linux.zip publish/linux/TES3Merge publish/linux/TES3Merge.ini

    # RELEASE
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
        artifacts: "TES3Merge-linux.zip"
        token: ${{ secrets.GITHUB_TOKEN }}


  publish-win:
    runs-on: windows-latest
    needs: publish-linux
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Publish
      run: dotnet publish TES3Merge/TES3Merge.csproj -o publish/win -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false

    # create zip
    - run: dir
    - run: Compress-Archive -LiteralPath "publish\win\TES3Merge.exe","publish\win\TES3Merge.ini" -DestinationPath "TES3Merge-win.zip"


    # RELEASE
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "TES3Merge-win.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
